execute pathogen#infect()
runtime macros/matchit.vim
syntax on

filetype plugin indent on

let g:netrw_liststyle=3
let g:netrw_alto=1
let g:netrw_altv=1
let g:netrw_localrmdir='rm -r'
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'

set nocp
set laststatus=2
set number
set relativenumber
set tabstop=2
set softtabstop=2
set shiftwidth=2
set smarttab
set expandtab
set backupdir=./.backup,.,/tmp
set directory=.,/.backup,/tmp
set complete=.,b,u,]
set runtimepath^=~/.vim/bundle/ctrlp.vim
set list
set incsearch
set hlsearch
set ignorecase

map <Enter> o<ESC>
map <S-Enter> O<ESC>

colorscheme slate
